name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker ub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Set Docker image tag
        id: tag
        run: echo "::set-output name=tag::${{ secrets.DOCKER_HUB_USERNAME }}/datalog-go:${{ github.sha }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}
          file: ./Dockerfile
          push: true
          tags: ${{ steps.tag.outputs.tag }}
